### ISSUE TITLE
App crashes if a different documentsui package name is used on system.

### ISSUE THREAD

**Issue by iamsigmainbs** [aliernfrog/lac-tool#108]
### **Description**
Some firmware uses a different package name for the files app.
Namely `com.android.documentsui` instead of `com.google.android.documentsui`.
Trying to find such an application causes the app to crash on startup.

`09-04 23:48:01.714 E/AndroidRuntime(32063): Caused by: android.content.pm.PackageManager$NameNotFoundException: com.google.android.documentsui`

### **Solution**
Use additional check with a different package name.

**Comment by aliernfrog** [comment]
Thanks for the report, with https://github.com/aliernfrog/lac-tool/commit/c945f1040c2b728a36c94223d92d522642753b41, the app should now check for `com.android.documentsui` if the other one fails, and skip the check if `com.android.documentsui` also fails.

Can you try and check if picking files/folders work fine with the latest commit? You can get the build from artifacts: https://github.com/aliernfrog/lac-tool/actions/runs/10715440236/artifacts/1894818410

**Comment by iamsigmainbs** [comment]
> Thanks for the report, with the [`fix/documentsui`](https://github.com/aliernfrog/lac-tool/tree/fix/documentsui) branch, the app should now check for both `com.google.android.documentsui` and `com.android.documentsui`, if both those checks fail it simply skips the files app restrictions check.
> 
> Can you try and check if picking files/folders work fine with this fix? You can get the build from artifacts: https://github.com/aliernfrog/lac-tool/actions/runs/10725127525/artifacts/1897540829

Great! App works great now, both normally and with shizuku.

**Comment by aliernfrog** [comment]
Thanks for testing, will release a new version shortly.
