### ISSUE TITLE
Persian language

### ISSUE THREAD

**Issue by MortezaMaxx** [aliernfrog/lac-tool#74]
Hello, you said on the crowdin site that if you want a new language to be added to the program, let me know on GitHub. Add the Persian language on the crowdin site so that I can translate

**Comment by aliernfrog** [comment]
Done.

**Comment by MortezaMaxx** [comment]
Hello, I have translated the Farsi language completely, the only thing left is for you to confirm it and add it to the lac tool program, thanks

**Comment by aliernfrog** [comment]
Thanks, i will add some new features in the upcoming days and release an update

**Comment by aliernfrog** [comment]
@MortezaMaxx Hi, I have pushed some new features and translations need to be updated, would appreciate it if you could translate them as well.

**Comment by MortezaMaxx** [comment]
ok sure

**Comment by MortezaMaxx** [comment]
Completed. Thank you for your cooperation in translation

**Comment by aliernfrog** [comment]
Thanks, releasing the update in a few minutes.
